# Generated by Django 4.1.7 on 2023-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_book_order_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prepared_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_by_user_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
